basePath: /my-playground-api
info:
  contact: {}
  description: '"My Playground API"'
  title: my-playground (backend/web)
  version: 0.0.1
paths: {}
securityDefinitions:
  BearerToken:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
